services:
  shecanak:
    build: .
    container_name: shecanak
    ports:
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./domains.csv:/domains.csv:ro
    restart: unless-stopped
