general:
  upstream_dns: udp://8.8.8.8:53
  bind_dns_over_udp: "0.0.0.0:53"
  bind_http: "0.0.0.0:80"
  bind_https: "0.0.0.0:443"
  log_level: info # choices: debug, info, warn, error

  # bind additional ports for HTTP. a list of ports or ranges separated by commas. example: "8080,8081-8083". follows the same listen address as bind_http
  bind_http_additional:

  # bind additional ports for HTTPS. a list of ports or ranges separated by commas. example: "8443,8444-8446". follows the same listen address as bind_https
  bind_https_additional:

  # Interface used for outbound TLS connections. uses OS preferred one if empty
  interface:

  # Preferred ip version for outgoing connections. choices: ipv4 (or 4), ipv6 (or 6), ipv4only, ipv6only, any. empty (or 0) means any.
  preferred_version: "ipv4only"

acl:
  domain:
    enabled: true
    priority: 1
    path: "/domains.csv"
    refresh_interval: 1000h0m0s
